{% set name = 'pandokia' %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0")
    +".dev"
    +environ.get("GIT_DESCRIBE_NUMBER", "0") %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu/testing/{{ name }}
    license: BSD
    summary: pandokia

build:
    number: {{ number }}
    string: py{{ CONDA_PY }}{{ GIT_DESCRIBE_HASH }}__{{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - nose
    - pytest
    - shunit2
    - setuptools
    - python x.x

    run:
    - nose
    - shunit2
    - pytest
    - python x.x

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - pdk --help
    imports:
    - pandokia
    - pandokia.runners
    - pandokia.helpers
